resolver: lts-13.19
packages:
- .
extra-deps:
- natural-transformation-0.4
- ./vendor/replica
# - ./vendor/concur-core
# - git: https://github.com/pkamenarsky/replica.git
#   commit: 69249ec760b8b8272d302269b54ddc4531d508a9
- git: https://github.com/ajnsit/concur.git
  commit: deef7cf42d193147abefb7f3b7ad2748a16368b8
  subdirs:
    - concur-core
flags: {}
extra-package-dbs: []
