resolver: lts-13.19
packages:
- .
extra-deps:
- natural-transformation-0.4
# - ./vendor/replica
# - ./vendor/concur-core
- git: https://github.com/pkamenarsky/replica.git
  commit: a46c17f6326eb154b2d76e31a1d62ed4b02a4a3c
- git: https://github.com/pkamenarsky/concur.git
  commit: 46d2fd3b2c236d573f1d6002eb58cc95b2ba03b9
  subdirs:
    - concur-core
flags: {}
extra-package-dbs: []
