resolver: lts-13.19
packages:
- .
extra-deps:
- natural-transformation-0.4
# - ./vendor/replica
# - ./vendor/concur-core
- git: https://github.com/pkamenarsky/replica.git
  commit: 4d93f16fe7397ee13a8842a01dad9224870c025e
- git: https://github.com/pkamenarsky/concur.git
  commit: 6c6bcc07b2688182945b28f154a013eee3f624c5
  subdirs:
    - concur-core
flags: {}
extra-package-dbs: []
